# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
  branches:
    include:
      - "*"

parameters:
  - name: debian_version
    type: string
    default: buster

variables:
  - name: BUILD_BRANCH
    ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      value: $(System.PullRequest.TargetBranch)
    ${{ else }}:
      value: $(Build.SourceBranchName)

stages:
- stage: Build

  jobs:
  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: amd64
      sonic_slave: sonic-slave-${{ parameters.debian_version }}
      common_lib_artifact_name: common-lib
      swss_common_artifact_name: sonic-swss-common
      sairedis_artifact_name: sonic-sairedis
      artifact_name: sonic-swss
      archive_pytests: true
      archive_gcov: true
      debian_version: ${{ parameters.debian_version }}

- stage: BuildArm
  dependsOn: Build
  condition: succeeded('Build')
  jobs:
  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: armhf
      pool: sonicbld-armhf
      sonic_slave: sonic-slave-${{ parameters.debian_version }}-armhf
      common_lib_artifact_name: common-lib.armhf
      swss_common_artifact_name: sonic-swss-common.armhf
      sairedis_artifact_name: sonic-sairedis.armhf
      artifact_name: sonic-swss.armhf
      archive_gcov: false
      debian_version: ${{ parameters.debian_version }}

  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: arm64
      pool: sonicbld-arm64
      sonic_slave: sonic-slave-${{ parameters.debian_version }}-arm64
      common_lib_artifact_name: common-lib.arm64
      swss_common_artifact_name: sonic-swss-common.arm64
      sairedis_artifact_name: sonic-sairedis.arm64
      artifact_name: sonic-swss.arm64
      archive_gcov: false
      debian_version: ${{ parameters.debian_version }}

- stage: BuildDocker
  dependsOn: Build
  condition: succeeded('Build')
  jobs:
  - template: .azure-pipelines/build-docker-sonic-vs-template.yml
    parameters:
      swss_common_artifact_name: sonic-swss-common
      sairedis_artifact_name: sonic-sairedis
      swss_artifact_name: sonic-swss
      artifact_name: docker-sonic-vs

- stage: Test
  dependsOn: BuildDocker
  condition: succeeded('BuildDocker')
  jobs:
  - template: .azure-pipelines/test-docker-sonic-vs-template.yml
    parameters:
      log_artifact_name: log
      gcov_artifact_name: sonic-gcov
      archive_gcov: true

- stage: Gcov
  dependsOn: Test
  condition: always()
  jobs:
  - template: .azure-pipelines/gcov.yml
    parameters:
      arch: amd64
      sonic_slave: sonic-slave-${{ parameters.debian_version }}
      swss_common_artifact_name: sonic-swss-common
      sairedis_artifact_name: sonic-sairedis
      swss_artifact_name: sonic-swss
      artifact_name: sonic-gcov
      archive_gcov: true
