# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
  branches:
    include:
      - "*"

stages:
- stage: Build

  jobs:
  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: amd64
      sonic_slave: sonic-slave-buster
      buildimage_artifact_name: sonic-buildimage.vs
      buildimage_pipeline: 142
      artifact_name: sonic-debs
      archive_pytests: true
      archive_gcov: true

- stage: BuildArm
  dependsOn: Build
  condition: succeeded('Build')
  jobs:
  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: armhf
      timeout: 240
      pool: sonicbld-armhf
      sonic_slave: sonic-slave-buster-armhf
      buildimage_artifact_name: sonic-buildimage.marvell-armhf
      buildimage_pipeline: 141
      artifact_name: sonic-swss.armhf
      archive_gcov: false

  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: arm64
      timeout: 240
      pool: sonicbld-arm64
      sonic_slave: sonic-slave-buster-arm64
      buildimage_artifact_name: sonic-buildimage.centec-arm64
      buildimage_pipeline: 140
      artifact_name: sonic-swss.arm64
      archive_gcov: false

- stage: BuildDocker
  dependsOn: Build
  condition: succeeded('Build')
  jobs:
  - template: .azure-pipelines/build-docker-sonic-vs-template.yml
    parameters:
      swss_artifact_name: sonic-debs
      artifact_name: docker-sonic-vs

- stage: Test
  dependsOn: BuildDocker
  condition: succeeded('BuildDocker')
  jobs:
  - template: .azure-pipelines/test-docker-sonic-vs-template.yml
    parameters:
      swss_artifact_name: sonic-debs
      log_artifact_name: log
      gcov_artifact_name: sonic-gcov
      archive_gcov: true

- stage: Gcov
  dependsOn: Test
  condition: always()
  jobs:
  - template: .azure-pipelines/gcov.yml
    parameters:
      arch: amd64
      sonic_slave: sonic-slave-buster
      artifact_name: sonic-gcov
      archive_gcov: true
