parameters:
- name: arch
  type: string
  values:
  - amd64
  - armhf
  - arm64
  default: amd64

- name: pool
  type: string
  values:
  - sonicbld
  - default
  default: default

- name: timeout
  type: number
  default: 60

- name: sonic_slave
  type: string

- name: sairedis_artifact_name
  type: string

- name: swss_common_artifact_name
  type: string

- name: artifact_name
  type: string

- name: archive_pytests
  type: boolean
  default: false

jobs:
- job:
  displayName: ${{ parameters.arch }}
  timeoutInMinutes: ${{ parameters.timeout }}

  pool:
    ${{ if ne(parameters.pool, 'default') }}:
      name: ${{ parameters.pool }}
    ${{ if eq(parameters.pool, 'default') }}:
      vmImage: 'ubuntu-20.04'

  container:
    image: sonicdev-microsoft.azurecr.io:443/${{ parameters.sonic_slave }}:latest

  steps:
  - script: |
      sudo apt-get install -y libhiredis0.14 libhiredis-dev
      sudo apt-get install -y libzmq5 libzmq3-dev
      sudo apt-get install -qq -y \
          libhiredis-dev \
          libnl-3-dev \
          libnl-genl-3-dev \
          libnl-route-3-dev \
          libnl-nf-3-dev \
          swig3.0
      sudo apt-get install -y libdbus-1-3
      sudo apt-get install -y libteam-dev \
          libteam5 \
          libteamdctl0
    displayName: "Install dependencies"
  - task: DownloadPipelineArtifact@2
    inputs:
      source: specific
      project: build
      pipeline: 9
      artifact: ${{ parameters.swss_common_artifact_name }}
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/201911'
    displayName: "Download sonic swss common deb packages"
  - task: DownloadPipelineArtifact@2
    inputs:
      source: specific
      project: build
      pipeline: 12
      artifact: ${{ parameters.sairedis_artifact_name }}
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/201911'
    displayName: "Download sonic sairedis deb packages"
  - task: DownloadPipelineArtifact@2
    inputs:
      source: specific
      project: build
      pipeline: 142
      artifact: sonic-buildimage.vs
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/201911'
      patterns: target/debs/stretch/*.deb
    displayName: "Download sonic image deb packages"
  - script: |
      pushd $(Pipeline.Workspace)/target/debs/stretch
      cp libhiredis0.14_*.deb \
         libhiredis-dev_*.deb \
         libnl-3-200_*.deb \
         libnl-3-dev_*.deb \
         libnl-genl-3-200_*.deb \
         libnl-genl-3-dev_*.deb \
         libnl-route-3-200_*.deb \
         libnl-route-3-dev_*.deb \
         libnl-nf-3-200_*.deb \
         libnl-nf-3-dev_*.deb \
         libnl-cli-3-200_*.deb \
         swig3.0_*.deb \
         $(Pipeline.Workspace)/
         cp libteam-dev_1.28-1_amd64.deb libteam5_1.28-1_amd64.deb libteamdctl0_1.28-1_amd64.deb $(Pipeline.Workspace)/
      popd
      ls -l $(Pipeline.Workspace)/*.deb
    displayName: "Copy deb packages"
  - script: |
      sudo apt-get install -y libzmq5 libzmq3-dev
      sudo dpkg -i --force-confask,confnew *.deb || sudo apt-get install -f -y
    workingDirectory: $(Pipeline.Workspace)
    displayName: "Install dependencies"
  - checkout: self
    submodules: true
  - script: |
      set -x
      tar czf pytest.tgz tests
      cp -r pytest.tgz $(Build.ArtifactStagingDirectory)/
      ./autogen.sh
      dpkg-buildpackage -us -uc -b -j$(nproc) && cp ../*.deb .
    displayName: "Compile sonic swss"
  - publish: $(System.DefaultWorkingDirectory)/
    artifact: ${{ parameters.artifact_name }}
    displayName: "Archive swss debian packages"
  - publish: $(Build.ArtifactStagingDirectory)/
    artifact: sonic-swss-pytests
    displayName: "Archive swss pytests"
    condition: eq('${{ parameters.archive_pytests }}', true)
