parameters:
- name: timeout
  type: number
  default: 180

- name: log_artifact_name
  type: string

jobs:
- job:
  displayName: vstest
  timeoutInMinutes: ${{ parameters.timeout }}

  pool:
    vmImage: 'ubuntu-20.04'

  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: docker-sonic-vs
    displayName: "Download docker sonic vs image"

  - task: DownloadPipelineArtifact@2
    inputs:
      source: specific
      project: build
      pipeline: 9
      artifact: sonic-swss-common.amd64.ubuntu20_04
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/master'
    displayName: "Download sonic swss common deb packages"

  - script: |
      set -x
      sudo .azure-pipelines/build_and_install_module.sh

      sudo apt-get install -y libhiredis0.14
      sudo dpkg -i --force-confask,confnew ../libswsscommon_1.0.0_amd64.deb || apt-get install -f
      sudo dpkg -i ../python3-swsscommon_1.0.0_amd64.deb

      # install packages for vs test
      sudo apt-get install -y net-tools bridge-utils vlan
      sudo apt-get install -y python3-pip
      sudo pip3 install pytest==4.6.2 attrs==19.1.0 exabgp==4.0.10 distro==1.5.0 docker==4.4.1 redis==3.3.4 flaky==3.7.0
      sudo apt-get install lcov
    displayName: "Install dependencies"

  - script: |
      set -x
      sudo docker load -i ../docker-sonic-vs.gz
      docker ps
      ip netns list
      pushd tests
      sudo py.test -v --force-flaky --junitxml=tr.xml --keeptb --imgname=docker-sonic-vs:$(Build.DefinitionName).$(Build.BuildNumber)
    displayName: "Run vs tests"

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/tr.xml'
      testRunTitle: vstest
    condition: always()

  - script: |
      cp -r tests/log $(Build.ArtifactStagingDirectory)/
      ./tests/gcov_support.sh merge_container_info $(Build.ArtifactStagingDirectory)
      docker stop $(docker ps -q -a) 
      docker rm $(docker ps -q -a)
    displayName: "Collect logs"
    condition: always()

  - publish: $(Build.ArtifactStagingDirectory)/
    artifact: ${{ parameters.log_artifact_name }}@$(System.JobAttempt)
    displayName: "Publish logs"
    condition: always()

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(Build.ArtifactStagingDirectory)/gcov_output/AllMergeReport/index.xml'
      reportDirectory: '$(Build.ArtifactStagingDirectory)/gcov_output/AllMergeReport/'
    displayName: 'Publish c c++ test coverage'
